// Generated by UwU_Snek's silly little Python script



package org.uwu_snek.shadownight._generated;
import org.bukkit.enchantments.Enchantment;
import org.jetbrains.annotations.NotNull;
import java.util.AbstractMap;
import java.util.Map;
public final class _enchantment_overrides extends org.uwu_snek.shadownight.utils.UtilityClass {
    private static final Map<String, Enchantment> overrides = Map.ofEntries(
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.reeling", Enchantment.BINDING_CURSE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused1", Enchantment.VANISHING_CURSE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused2", Enchantment.SWEEPING_EDGE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused3", Enchantment.FROST_WALKER),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused4", Enchantment.MENDING),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused5", Enchantment.SOUL_SPEED),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused6", Enchantment.SWIFT_SNEAK),

        new AbstractMap.SimpleEntry<>("enchantment.minecraft.aqua_affinity", Enchantment.WATER_WORKER),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.bane_of_arthropods", Enchantment.DAMAGE_ARTHROPODS),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.blast_protection", Enchantment.PROTECTION_EXPLOSIONS),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.channeling", Enchantment.CHANNELING),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.depth_strider", Enchantment.DEPTH_STRIDER),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.efficiency", Enchantment.DIG_SPEED),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.feather_falling", Enchantment.PROTECTION_FALL),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.fire_aspect", Enchantment.FIRE_ASPECT),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.fire_protection", Enchantment.PROTECTION_FIRE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.flame", Enchantment.ARROW_FIRE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.fortune", Enchantment.LOOT_BONUS_BLOCKS),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.impaling", Enchantment.IMPALING),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.infinity", Enchantment.ARROW_INFINITE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.knockback", Enchantment.KNOCKBACK),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.looting", Enchantment.LOOT_BONUS_MOBS),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.loyalty", Enchantment.LOYALTY),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.luck_of_the_sea", Enchantment.LUCK),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.lure", Enchantment.LURE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.multishot", Enchantment.MULTISHOT),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.piercing", Enchantment.PIERCING),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.power", Enchantment.ARROW_DAMAGE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.projectile_protection", Enchantment.PROTECTION_PROJECTILE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.protection", Enchantment.PROTECTION_ENVIRONMENTAL),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.punch", Enchantment.ARROW_KNOCKBACK),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.quick_charge", Enchantment.QUICK_CHARGE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.respiration", Enchantment.OXYGEN),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.riptide", Enchantment.RIPTIDE),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.sharpness", Enchantment.DAMAGE_ALL),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.silk_touch", Enchantment.SILK_TOUCH),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.smite", Enchantment.DAMAGE_UNDEAD),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.thorns", Enchantment.THORNS),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unbreaking", Enchantment.DURABILITY)
    );

    private static final Map<String, String> realNames = Map.ofEntries(
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.reeling", "Reeling"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.binding_curse", "Curse of Binding"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused1", "unused1"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.vanishing_curse", "Curse of Vanishing"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused2", "unused2"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.sweeping", "Sweeping Edge"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused3", "unused3"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.frost_walker", "Frost Walker"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused4", "unused4"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.mending", "Mending"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused5", "unused5"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.soul_speed", "Soul Speed"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unused6", "unused6"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.swift_sneak", "Swift Sneak"),

        new AbstractMap.SimpleEntry<>("enchantment.minecraft.aqua_affinity", "Aqua Affinity"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.bane_of_arthropods", "Bane of Arthropods"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.blast_protection", "Blast Protection"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.channeling", "Channeling"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.depth_strider", "Depth Strider"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.efficiency", "Efficiency"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.feather_falling", "Feather Falling"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.fire_aspect", "Fire Aspect"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.fire_protection", "Fire Protection"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.flame", "Flame"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.fortune", "Fortune"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.impaling", "Impaling"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.infinity", "Infinity"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.knockback", "Knockback"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.looting", "Looting"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.loyalty", "Loyalty"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.luck_of_the_sea", "Luck of the Sea"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.lure", "Lure"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.multishot", "Multishot"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.piercing", "Piercing"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.power", "Power"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.projectile_protection", "Projectile Protection"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.protection", "Protection"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.punch", "Punch"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.quick_charge", "Quick Charge"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.respiration", "Respiration"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.riptide", "Riptide"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.sharpness", "Sharpness"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.silk_touch", "Silk Touch"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.smite", "Smite"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.thorns", "Thorns"),
        new AbstractMap.SimpleEntry<>("enchantment.minecraft.unbreaking", "Unbreaking")
    );

    public static Enchantment getOverride(final @NotNull String e){ return overrides.get(e); }

    private static final String[] lvlDisplay = new String[]{ "", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX" };
    public static String getRealDisplayName(final @NotNull String e, final int lvl){ return realNames.get(e) + " " + (lvl > 20 ? lvl : lvlDisplay[lvl]); }
}