// Generated by UwU_Snek's silly little Python script



package org.uwu_snek.shadownight._generated;
public enum _mob_part_type {
    DEBUG_MOB_PART(20000),
    OVERGROWN_SPIDER_LEG_0(20001);
    private final int modelData;
    _mob_part_type(final int _modelData) {
        this.modelData = _modelData;
    }
    public int getCustomModelData() {
        return modelData;
    }
}