// Generated by UwU_Snek's silly little Python script



package org.uwu_snek.shadownight._generated;
public enum _mob_part_type {
    DUNGEONS_OVERGROWN_SPIDER_CORE(20000),
    DUNGEONS_OVERGROWN_SPIDER_HEAD(20001),
    DUNGEONS_OVERGROWN_SPIDER_LEG_0B(20002),
    DUNGEONS_OVERGROWN_SPIDER_LEG_00(20003),
    DUNGEONS_OVERGROWN_SPIDER_LEG_01(20004),
    DUNGEONS_OVERGROWN_SPIDER_LEG_02(20005),
    DUNGEONS_OVERGROWN_SPIDER_LEG_0A(20006),
    DEBUG_MOB_MAIN(20007),
    ;
    private final int modelData;
    _mob_part_type(final int _modelData) {
        this.modelData = _modelData;
    }
    public int getCustomModelData() {
        return modelData;
    }
}