// Generated by UwU_Snek's silly little Python script



package org.uwu_snek.shadownight._generated._mob_presets;
import org.uwu_snek.shadownight.customMobs.MOB;
import org.uwu_snek.shadownight._generated._mob_part_type;
import org.uwu_snek.shadownight.customMobs.Bone;
import org.uwu_snek.shadownight.customMobs.DisplayBone;
public abstract class _mob_preset_dungeons_overgrown_spider extends MOB {
    protected Bone head = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_HEAD, 1.02f, 1.02f);
    protected Bone leg_fl0 = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_LEG_FL0, 1.02f, 1.02f);
    protected Bone leg_fl1 = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_LEG_FL1, 1.02f, 1.02f);
    protected Bone leg_fl2 = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_LEG_FL2, 1.02f, 1.02f);

    public _mob_preset_dungeons_overgrown_spider() {
        super();
        root.addChild(head);
        root.addChild(leg_fl0);
        leg_fl0.addChild(leg_fl1);
        leg_fl1.addChild(leg_fl2);
    }
}
