// Generated by UwU_Snek's silly little Python script



package org.uwu_snek.shadownight._generated._mob_presets;
import org.uwu_snek.shadownight.customMobs.MOB;
import org.uwu_snek.shadownight._generated._mob_part_type;
import org.uwu_snek.shadownight.customMobs.Bone;
import org.uwu_snek.shadownight.customMobs.DisplayBone;
public abstract class _mob_preset_dungeons_overgrown_spider extends MOB {
    protected Bone head = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_HEAD, 0.5f, 0.5f);
    protected Bone leg_00 = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_LEG_00, 0.5f, 0.5f);
    protected Bone leg_01 = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_LEG_01, 0.5f, 0.5f);
    protected Bone leg_02 = new DisplayBone(_mob_part_type.DUNGEONS_OVERGROWN_SPIDER_LEG_02, 0.5f, 0.5f);

    public _mob_preset_dungeons_overgrown_spider() {
        super();
        root.addChild(head);
        root.addChild(leg_00);
        leg_00.addChild(leg_01);
        leg_01.addChild(leg_02);
        head.moveSelf(20, 0.0f, 0.0f, 0.0f);
        leg_00.moveSelf(20, -0.40625f, -0.34375f, 0.0f);
        leg_01.moveSelf(20, -0.8125f, 0.40625f, 0.0f);
        leg_02.moveSelf(20, -1.015625f, -0.09375f, 0.0f);
    }
}
